apiVersion: v1
kind: Template
metadata:
  name: conprof-observatorium-logs-rbac
objects:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    labels:
      app.kubernetes.io/instance: conprof
      app.kubernetes.io/name: conprof
      app.kubernetes.io/version: ${IMAGE_TAG}
    name: conprof-${NAMESPACE}
  rules:
  - apiGroups:
    - ""
    resources:
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    labels:
      app.kubernetes.io/instance: conprof
      app.kubernetes.io/name: conprof
      app.kubernetes.io/version: ${IMAGE_TAG}
    name: conprof-${NAMESPACE}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: conprof-${NAMESPACE}
  subjects:
  - kind: ServiceAccount
    name: prometheus-telemeter
    namespace: ${NAMESPACE}
parameters:
- name: NAMESPACE
  value: observatorium-logs
